use_frameworks!

target 'WBSegmentControl_Example', :exclusive => true do
  pod 'WBSegmentControl', :path => '../'
  pod 'SnapKit'
  pod 'SwiftHEXColors'
end

target 'WBSegmentControl_Tests', :exclusive => true do
  pod 'WBSegmentControl', :path => '../'

  pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
